include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: ignore
    curly_braces_in_flow_control_structures: ignore
    dangling_library_doc_comments: ignore
    deprecated_member_use: ignore
    prefer_final_fields: ignore
    prefer_if_null_operators: ignore
    unnecessary_const: ignore
    unnecessary_import: ignore
    unnecessary_underscores: ignore
    use_build_context_synchronously: ignore
